### ISSUE TITLE
您好，想请教您一个问题

### ISSUE THREAD

**Issue by beiguancyc** [leancloud/leanchat-cloudcode#4]
最近刚开始接触leanCloud的云引擎，但是因为没做过js，加上leancloud的文档过于分散，一直步履维艰。我想实现客户端a将一条数据保存到数据库，然后通过云引擎的aftersave的hook给客户端b发送一条消息“已经保存”，请问云引擎能这么工作吗？

**Comment by wangxiao** [comment]
可以这样工作。云引擎的 hook 其实就是一些写好了的 REST API 接口，可以控制它的 http response。

**Comment by beiguancyc** [comment]
感谢您的指点。
